### ISSUE TITLE
Fix NJ, HI and Baltimore maps

### ISSUE THREAD

**Issue by edgararuiz** [sol-eng/access-to-care#3]

**Comment by nwstephens** [comment]
Baltimore is exceptional in that it does not belong to a county, only a city. So the map looks odd.

![image](https://user-images.githubusercontent.com/7519295/55496108-53616980-560c-11e9-9af3-98c569ded818.png)

**Comment by edgararuiz** [comment]
It looks like the location of hospitals for the following states are missing in the original data:

```
hospitals %>%
+     filter(is.na(longitude)) %>%
+     count(state)
# A tibble: 8 x 2
  state     n
  <chr> <int>
1 CT       31
2 MA       64
3 ME       33
4 NH       26
5 NJ       66
6 RI       11
7 VI        2
8 VT       14
```

May be better to just remove these states from the dropdown selections. But will search for a solution that adds the hospitals

**Comment by nwstephens** [comment]
I don't think you have a choice but to remove these states.
